// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace BinOdonto
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"cep_cliente_num")]
            public float Cep_cliente_num { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"cep_funcionario_num")]
            public float Cep_funcionario_num { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"diferenca_ceps")]
            public float Diferenca_ceps { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"mesmo_prefixo")]
            public bool Mesmo_prefixo { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"proximo")]
            public bool Proximo { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"cep_cliente_num")]
            public float Cep_cliente_num { get; set; }

            [ColumnName(@"cep_funcionario_num")]
            public float Cep_funcionario_num { get; set; }

            [ColumnName(@"diferenca_ceps")]
            public float Diferenca_ceps { get; set; }

            [ColumnName(@"mesmo_prefixo")]
            public float[] Mesmo_prefixo { get; set; }

            [ColumnName(@"proximo")]
            public bool Proximo { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public bool PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

            [ColumnName(@"Probability")]
            public float Probability { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
